<?php

namespace GamesBundle\Repository;

/**
 * PlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformRepository extends \Doctrine\ORM\EntityRepository
{
}
