<?php

namespace GamesBundle\Repository;

/**
 * ScreenshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScreenshotRepository extends \Doctrine\ORM\EntityRepository
{
}
